apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-frontend
  namespace: default
  labels:
    app: app
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
      component: frontend
  template:
    metadata:
      labels:
        app: app
        component: frontend
    spec:
      containers:
        - name: frontend
          image: k3d-cicd-registry:5050/app-frontend:v3.9.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 256Mi
              cpu: 500m
