apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
images:
  - name: todo-backend
    newName: {{ REGISTRY }}/todo-backend
    newTag: {{ IMAGE_TAG }}
  - name: todo-frontend
    newName: {{ REGISTRY }}/todo-frontend
    newTag: {{ IMAGE_TAG }}
resources:
  - backend/deployment.yaml
  - backend/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
