apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
images:
  - name: todo-backend
    newName: k3d-cicd-registry:5050/todo-backend
    newTag: latest
  - name: todo-frontend
    newName: k3d-cicd-registry:5050/todo-frontend
    newTag: latest
resources:
  - backend/deployment.yaml
  - backend/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
