apiVersion: v1
kind: Service
metadata:
  name: app-backend
  namespace: default
  labels:
    app: app
    component: backend
spec:
  type: ClusterIP
  selector:
    app: app
    component: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
